### ISSUE TITLE
Missing AAR file in 1.4.0 Release

### ISSUE THREAD

**Issue by jfreeley** [GitLiveApp/firebase-kotlin-sdk#200]
Hi,

There seems to be an issue with a missing AAR file again in the 1.4.0 release as happened with the 1.3.0 release https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/185. I'm guessing it's the same issue. 

The `firebase-common-android-debug-1.4.0.aar` is the missing file in https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.4.0/

@Reedyuk resolved the issue last time, so perhaps you could fix the issue again.

Thanks

**Comment by nphau** [comment]
[``[](url)](url)
<img width="1086" alt="Screen Shot 2021-07-10 at 16 59 26" src="https://user-images.githubusercontent.com/13111806/125159271-a25db800-e1a0-11eb-8212-8bdb94601c55.png">
<img width="566" alt="Screen Shot 2021-07-10 at 16 59 43" src="https://user-images.githubusercontent.com/13111806/125159274-a558a880-e1a0-11eb-88c5-c4c11d5c8c6c.png">

Me too, can you check @Reedyuk

**Comment by Reedyuk** [comment]
Thats odd, i have just published 1.4.1, i checked and it appears it's there this time, but i have feeling this issue might crop up again.
<img width="480" alt="Screenshot 2021-07-16 at 11 31 00" src="https://user-images.githubusercontent.com/3853006/125934714-aaf80c41-d0d4-40e5-aca7-e0b4aec82098.png">

**Comment by Reedyuk** [comment]
Can you confirm if this is working now? i have just published it so might need to wait atleast one hour from now until it appears.

**Comment by kkalisz** [comment]
Hi, @Reedyuk I have just found the same issue (but other artifact) on 1.4.1 

**1.4.0**
https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.4.0 - aar missing
https://repo.maven.apache.org/maven2/dev/gitlive/firebase-app-android-debug/1.4.0 - aar present

**1.4.1**
https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.4.1 - aar present
https://repo.maven.apache.org/maven2/dev/gitlive/firebase-app-android-debug/1.4.1 - aar missing


For 1.3.1 both artifact are present in artifactory. 
I have also check other artifacts for 1.4.1 and 1.4.0 and it looks that aar files are in place

**Comment by nphau** [comment]
Still the same 
<img width="1070" alt="Screen Shot 2021-07-20 at 11 18 43" src="https://user-images.githubusercontent.com/13111806/126261262-7ab51e64-b8b7-44a2-8b3c-b00ab9974263.png">

**Comment by gbirk** [comment]
For me as well:

implementation("dev.gitlive:firebase-firestore:1.4.1")

<img width="1308" alt="Screen Shot 2021-07-21 at 12 57 45 PM" src="https://user-images.githubusercontent.com/23461430/126520739-96021942-f0e8-42c3-ba75-04f35bd660d7.png">

**Comment by gbirk** [comment]
Do we have any workaround for this problem?

**Comment by tiagonuneslx** [comment]
> Do we have any workaround for this problem?

You could build and publish the project locally

**Comment by suntrix** [comment]
> Any update on this issue? 1.4.1 and have this issue
> 
> @tiagonuneslx sorry, I am a bit stupid when it comes to this. I tried `publishToMavenLocal` have the library and all the .aar files in the local maven repo (on my disk) but I cannot to get it to compile. It's still erroring the same way, added mavenLocal as the repository, tried adding src/libs and some other methods I've found. Could you please provide a short summary on steps needed to get it to work?

Workaround with `publishToMavenLocal` will work if you change the lib version (e.g. 1.4.1-local), it's because 1.4.1 is already cached in your local Gradle. You can also remove your Gradle cache (usually ~/.gradle/caches/*), but this will make all the dependencies to re-download.

**Comment by Reedyuk** [comment]
I have not had time to diagnose the problem its either a problem with the maven publish plugin or with the CI (github actions/sonartype).
When the release is made, it uploads it in two groups to sonartype and when i try to release this it fails complaining one of the groups is not signed(this group contains the missing package/aar file). It seems entirely random too, sometimes its firebase app, sometimes its common.
If anyone has come across this issue before, it would be helpful, i think its a bug with the maven publish plugin but havent had time to diagnose.

**Comment by HeyItsMedz** [comment]
Also getting this error with 1.4.1

![image](https://user-images.githubusercontent.com/14113823/130351650-22aa5b49-0d98-4f14-8342-3c9c30a1eb5c.png)

**Comment by suntrix** [comment]
> I have not had time to diagnose the problem its either a problem with the maven publish plugin or with the CI (github actions/sonartype).
> When the release is made, it uploads it in two groups to sonartype and when i try to release this it fails complaining one of the groups is not signed(this group contains the missing package/aar file). It seems entirely random too, sometimes its firebase app, sometimes its common.
> If anyone has come across this issue before, it would be helpful, i think its a bug with the maven publish plugin but havent had time to diagnose.

@Reedyuk It looks like an issue with signing. I tested pure maven publish with GitHub packages on my repo fork. Everything's working fine & the multiplatform app that I'm using it with is happy. Here's a diff of what I've changed: https://github.com/GitLiveApp/firebase-kotlin-sdk/compare/master...suntrix:master-internal

**Comment by suntrix** [comment]
@Reedyuk 

I came across this issue today while publishing to GitHub Maven repo & it was failing with random package variants, so this might be the underlying cause of your issue -> https://github.com/gradle/gradle/issues/11308

I added the suggested setting to gradle.properties in my PR (https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/215/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19).

**Comment by Reedyuk** [comment]
@suntrix I have merged in and just a moment ago released 1.4.2, give it an hour and can you confirm it worked or not.
I'm still not 100% sure it was resolved, so let me know.

**Comment by Nikola-Milovic** [comment]
@Reedyuk  
```
Unable to build Kotlin project configuration

org.gradle.internal.resolve.ArtifactNotFoundException: Could not find firebase-app-debug.aar (dev.gitlive:firebase-app-android-debug:1.4.2).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/dev/gitlive/firebase-app-android-debug/1.4.2/firebase-app-android-debug-1.4.2.aar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:28)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:345)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:297)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$15(ErrorHandlingModuleComponentRepository.java:181)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:237)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:203)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:179)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:273)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:244)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:216)
	at org.gradle.internal.Try.ofFailable(Try.java:39)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:211)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:184)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:175)
	at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.finalizeValue(TransformingAsyncArtifactListener.java:176)
	at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.run(TransformingAsyncArtifactListener.java:125)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:241)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:222)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:212)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:70)
	at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:212)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:172)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by suntrix** [comment]
@Reedyuk confirmed - AARs are still missing :(

I found this https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

**Comment by regentropft** [comment]
same problem occurs with dev.gitlive:firebase-database:1.4.X releases

**Comment by michaelbukachi** [comment]
@Reedyuk Any updates on this?

**Comment by Reedyuk** [comment]
This issue is now fixed from version 1.4.3 onwards.
